### ISSUE TITLE
Difference between examples and reverse patching

### ISSUE THREAD

**Issue by amlwwalker** [gabstv/go-bsdiff#3]
Hello!
I have been looking to see if anyone has implemented bsdiff directly into Go. Lovely work!

1. I was wondering what the difference between the two examples is in your README.md, in terms of you have Bsdiff Bytes and Bsdiff Reader - is it just a way to literally view the diff?

2. I am interested in reversing patches, rather than applying patches to old files, to get new ones.

So for instance if I have files

v0.1
v0.2
v0.3

and I want to get from v0.3 to v0.1 I want to reverse the patch from v0.3 -> v0.2 and then reverse the patch from 0.2 to v0.1
Is this possible do you know, or do you know what it would involve?

Thanks
Alex!

**Comment by gabstv** [comment]
Hi!

1 -> The examples have different return types (`[]byte`, `io.Reader`) just for convenience, to be easily plugged in a database.

To get the reverse patches, you would have to have a patch from v0.3 to v0.2 (doing `bsdiff fileV2 filev3`). Maybe there is a reverse patch technique (so you could use the same patch), but I'm not aware of this technique.
