### ISSUE TITLE
Passing a channel so a diff can be cancelled

### ISSUE THREAD

**Issue by amlwwalker** [gabstv/go-bsdiff#4]
Hi (again...)
If I wanted to cancel a diff, for instance if it was diffing a large file and I wanted to stop it, could a helper function that takes a channel be used?
Im prodding around in your code, but it's pretty full on code and In worried im poking around in areas I am not familiar with and could cause problems.
Any suggestion would be very helpful as to where to check for a message on a channel to cancel whatever is going on.

Thanks
A

**Comment by gabstv** [comment]
Hi,

You could pass a context to `diffb` like:
```go
func diffb(ctx context.Context, oldbin, newbin []byte) ([]byte, error) {
    // ...
    // at every cancellable step:
    if ctx.Err() != nil {
        return nil, fmt.Errorf("context: %v", err.Error())
    }
}
```
And create a public method like `BytesCtx(ctx context.Context, oldbin, newbin []byte)`, then pass the context:
```go
d := time.Now().Add(50 * time.Second)
ctx, cancel := context.WithDeadline(context.Background(), d)
patch, err := bsdiff.BytesCtx(ctx, oldbin, newbin)
```
